///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QuotationListResponseDataItemsMerchant {
/*
{
  "id": 97,
  "name": "Toko Jual Apa Saja",
  "picture": null
} 
*/

  int? id;
  String? name;
  String? picture;

  QuotationListResponseDataItemsMerchant({
    this.id,
    this.name,
    this.picture,
  });
  QuotationListResponseDataItemsMerchant.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    picture = json['picture']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['picture'] = picture;
    return data;
  }
}

class QuotationEntity {
/*
{
  "id": 13,
  "name": "Pengadaan 1",
  "desc": "Desc pegnadaan",
  "status": 1,
  "status_name": "Requested",
  "status_code": "Requested",
  "budget": "1500000.00",
  "currency": "IDR",
  "currency_id": 1,
  "deadline": "2022-04-26T07:29:00.000Z",
  "merchant": {
    "id": 97,
    "name": "Toko Jual Apa Saja",
    "picture": null
  }
} 
*/

  int? id;
  String? name;
  String? desc;
  int? status;
  String? statusName;
  String? statusCode;
  String? budget;
  String? currency;
  int? currencyId;
  String? deadline;
  QuotationListResponseDataItemsMerchant? merchant;

  QuotationEntity({
    this.id,
    this.name,
    this.desc,
    this.status,
    this.statusName,
    this.statusCode,
    this.budget,
    this.currency,
    this.currencyId,
    this.deadline,
    this.merchant,
  });
  QuotationEntity.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    desc = json['desc']?.toString();
    status = json['status']?.toInt();
    statusName = json['status_name']?.toString();
    statusCode = json['status_code']?.toString();
    budget = json['budget']?.toString();
    currency = json['currency']?.toString();
    currencyId = json['currency_id']?.toInt();
    deadline = json['deadline']?.toString();
    merchant = (json['merchant'] != null) ? QuotationListResponseDataItemsMerchant.fromJson(json['merchant']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['desc'] = desc;
    data['status'] = status;
    data['status_name'] = statusName;
    data['status_code'] = statusCode;
    data['budget'] = budget;
    data['currency'] = currency;
    data['currency_id'] = currencyId;
    data['deadline'] = deadline;
    if (merchant != null) {
      data['merchant'] = merchant!.toJson();
    }
    return data;
  }
}

class QuotationListResponse {

  int? currentItems;
  int? totalItems;
  int? currentPage;
  int? totalPages;
  List<QuotationEntity?>? items;

  QuotationListResponse({
    this.currentItems,
    this.totalItems,
    this.currentPage,
    this.totalPages,
    this.items,
  });

  QuotationListResponse.fromJson(Map<String, dynamic> json) {
    currentItems = json['currentItems']?.toInt();
    totalItems = json['totalItems']?.toInt();
    currentPage = json['currentPage']?.toInt();
    totalPages = json['totalPages']?.toInt();
  if (json['items'] != null) {
  final v = json['items'];
  final arr0 = <QuotationEntity>[];
  v.forEach((v) {
  arr0.add(QuotationEntity.fromJson(v));
  });
    items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['currentItems'] = currentItems;
    data['totalItems'] = totalItems;
    data['currentPage'] = currentPage;
    data['totalPages'] = totalPages;
    if (items != null) {
      final v = items;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['items'] = arr0;
    }
    return data;
  }
}