///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderAcceptResponseData {
/*
{
  "accepted": true,
  "order_id": 163,
  "accepted_date": "2022-03-16T05:15:43.000Z"
} 
*/

  bool? accepted;
  int? orderId;
  String? acceptedDate;

  OrderAcceptResponseData({
    this.accepted,
    this.orderId,
    this.acceptedDate,
  });
  OrderAcceptResponseData.fromJson(Map<String, dynamic> json) {
    accepted = json['accepted'];
    orderId = json['order_id']?.toInt();
    acceptedDate = json['accepted_date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['accepted'] = accepted;
    data['order_id'] = orderId;
    data['accepted_date'] = acceptedDate;
    return data;
  }
}

class OrderAcceptResponse {
/*
{
  "statusCode": "200",
  "message": "Success",
  "data": {
    "accepted": true,
    "order_id": 163,
    "accepted_date": "2022-03-16T05:15:43.000Z"
  }
} 
*/

  String? statusCode;
  String? message;
  OrderAcceptResponseData? data;

  OrderAcceptResponse({
    this.statusCode,
    this.message,
    this.data,
  });
  OrderAcceptResponse.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode']?.toString();
    message = json['message']?.toString();
    data = (json['data'] != null) ? OrderAcceptResponseData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
