///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserAddressResponse {
/*
{
  "user_address_id": 26,
  "user_id": 125,
  "address_name": "Rumah",
  "address_1": "sudirman",
  "address_2": "kode",
  "city": "Jakarta Pusat",
  "state": "DKI Jakarta",
  "country": "INDONESIA",
  "postal_code": "10650",
  "address_tag": "Rumah",
  "is_primary": true,
  "ref_shipper_country_id": 228,
  "ref_shipper_province_id": 6,
  "ref_shipper_city_id": 43,
  "ref_shipper_suburb_id": 501,
  "ref_shipper_area_id": 4835,
  "created_date": "2022-04-26T15:01:00.000Z",
  "updated_date": "2022-04-26T15:01:00.000Z",
  "note": null,
  "suburb": null,
  "area": null,
  "phone": "082220201121"
} 
*/

  int? userAddressId;
  int? userId;
  String? addressName;
  String? address1;
  String? address2;
  String? city;
  String? state;
  String? country;
  String? postalCode;
  String? addressTag;
  bool? isPrimary;
  int? refShipperCountryId;
  int? refShipperProvinceId;
  int? refShipperCityId;
  int? refShipperSuburbId;
  int? refShipperAreaId;
  String? createdDate;
  String? updatedDate;
  String? note;
  String? suburb;
  String? area;
  String? phone;

  UserAddressResponse({
    this.userAddressId,
    this.userId,
    this.addressName,
    this.address1,
    this.address2,
    this.city,
    this.state,
    this.country,
    this.postalCode,
    this.addressTag,
    this.isPrimary,
    this.refShipperCountryId,
    this.refShipperProvinceId,
    this.refShipperCityId,
    this.refShipperSuburbId,
    this.refShipperAreaId,
    this.createdDate,
    this.updatedDate,
    this.note,
    this.suburb,
    this.area,
    this.phone,
  });
  UserAddressResponse.fromJson(Map<String, dynamic> json) {
    userAddressId = json['user_address_id']?.toInt();
    userId = json['user_id']?.toInt();
    addressName = json['address_name']?.toString();
    address1 = json['address_1']?.toString();
    address2 = json['address_2']?.toString();
    city = json['city']?.toString();
    state = json['state']?.toString();
    country = json['country']?.toString();
    postalCode = json['postal_code']?.toString();
    addressTag = json['address_tag']?.toString();
    isPrimary = json['is_primary'];
    refShipperCountryId = json['ref_shipper_country_id']?.toInt();
    refShipperProvinceId = json['ref_shipper_province_id']?.toInt();
    refShipperCityId = json['ref_shipper_city_id']?.toInt();
    refShipperSuburbId = json['ref_shipper_suburb_id']?.toInt();
    refShipperAreaId = json['ref_shipper_area_id']?.toInt();
    createdDate = json['created_date']?.toString();
    updatedDate = json['updated_date']?.toString();
    note = json['note']?.toString();
    suburb = json['suburb']?.toString();
    area = json['area']?.toString();
    phone = json['phone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_address_id'] = userAddressId;
    data['user_id'] = userId;
    data['address_name'] = addressName;
    data['address_1'] = address1;
    data['address_2'] = address2;
    data['city'] = city;
    data['state'] = state;
    data['country'] = country;
    data['postal_code'] = postalCode;
    data['address_tag'] = addressTag;
    data['is_primary'] = isPrimary;
    data['ref_shipper_country_id'] = refShipperCountryId;
    data['ref_shipper_province_id'] = refShipperProvinceId;
    data['ref_shipper_city_id'] = refShipperCityId;
    data['ref_shipper_suburb_id'] = refShipperSuburbId;
    data['ref_shipper_area_id'] = refShipperAreaId;
    data['created_date'] = createdDate;
    data['updated_date'] = updatedDate;
    data['note'] = note;
    data['suburb'] = suburb;
    data['area'] = area;
    data['phone'] = phone;
    return data;
  }
}
